# This file is generated by https://github.com:pylover/python-makelib
import os.path
import re

from setuptools import setup, find_packages


# reading package's version (same way sqlalchemy does)
with open(
    os.path.join(os.path.dirname(__file__), 'yconf', '__init__.py')
) as v_file:
    package_version = \
        re.compile('.*__version__ = \'(.*?)\'', re.S) \
        .match(v_file.read()) \
        .group(1)


dependencies = [
    # TODO: dependencies
]


setup(
    name='yconf',
    version=package_version,
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',  # This is important!
    install_requires=dependencies,
    packages=find_packages(
        where='.',
        include=['yconf'],
        exclude=['tests']
    ),
    # TODO: entrypoints
    # TODO: classifiers
)
